services:
  payment:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8081:8080"
    networks:
      - bankirka_app-network

networks:
  bankirka_app-network:
    external: true


